### ISSUE TITLE
Split client and API

### ISSUE THREAD

**Issue by lucasfeliciano** [skellock/reactotron#10]
Why don't you split the client ( binary ) to another repo like `reactotron-cli` so you can install it globally and therefore in the `devDependencies` of your project you just add the javascript api `reactotron` to connect to the client?

**Comment by skellock** [comment]
I was really torn about how to implement this.  What you're saying is totally legit.

I ended up going with a unified library instead because it's all just `devDependencies` anyway.  You can still install it via npm globally if you wish, but some people get squirrely with that.

I'll keep this in mind though as we go.  It might have to be something I reconsider when adding the `react-dom` support too.

**Comment by skellock** [comment]
I've got a new version coming out that splits this as you've suggested.  Thank you.
