### ISSUE TITLE
socket.io seems to be a pre-built...

### ISSUE THREAD

**Issue by seethroughtrees** [skellock/reactotron#53]
Very anxious to try this out, looks incredible.  

However, when adding the initial config, just like the ReactDOM example:

I get this running webpack:

```
WARNING in ./~/socket.io-client/socket.io.js
Critical dependencies:
1:475-482 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/socket.io-client/socket.io.js 1:475-482
```

I have tried installing socket.io and socket.io-client directly.  

Any ideas?

Thanks in advance.

**Comment by skellock** [comment]
I too have seen that.  Not quite sure what that's all about.  That's exactly what we want.  The prebuilt version.  I'll dig a bit more into that and get some answers.

**Comment by skellock** [comment]
So, you're right.  For webpack, we should be using:

`var io = require('socket.io-client')`

However on React Native we need to use:

`var io = require('socket.io-client/socket.io')`

Webpack wants use the non-prebuilt version because it can do a better job of optimizing what needs to be in the build.

So.... I need to be able to detect that we're running in a webpack environment and require `socket.io` the right way per-platform.

In the meantime, it's ok to ignore this warning.  Or if you want the warning to just go away for now:

Add a `noParse: [ /socket.io/ ] ` entry to your `module` section to your webpack config:

![image](https://cloud.githubusercontent.com/assets/68273/14935817/530e39b2-0ead-11e6-88ab-55cea64f5e6c.png)

**Comment by seethroughtrees** [comment]
That did the trick!  Thanks @skellock ... It was actually more than a warning as it was preventing Webpack from compiling.  So hopefully this helps some other people too.

Thanks again!
